# Этап сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Копируем файл проекта и восстанавливаем зависимости
COPY RabotaGovnoClone.csproj .
RUN dotnet restore

# Копируем все остальные файлы и публикуем приложение
COPY . .
RUN dotnet publish -c Release -o /app/publish

# Этап запуска
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Копируем опубликованные файлы из этапа сборки
COPY --from=build /app/publish .

# Указываем порт, который будет слушать приложение
ENV ASPNETCORE_URLS=http://+:5090
EXPOSE 5090

# Запускаем приложение
ENTRYPOINT ["dotnet", "RabotaGovnoClone.dll"]